services:
  goofish-watcher:
    build: .
    container_name: goofish-watcher
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cookies.json:/app/cookies.json
      - ./chrome_profile:/app/chrome_profile
    environment:
      - GOOFISH_COOKIES_JSON_PATH=/app/cookies.json
